services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --appendonly yes --appendfsync everysec
    volumes:
      - redis_data:/data
    networks:
      - internal

  backend:
    build: ./backend
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./backend/src:/app/src
      - ./backend/main.py:/app/main.py
    depends_on:
      - redis
    networks:
      - internal

  # frontend:
  #   build:
  #     context: ./frontend
  #     args:
  #       VITE_API_URL: http://localhost:8000
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
  #   networks:
  #     - internal

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - backend
    networks:
      - internal

volumes:
  redis_data:

networks:
  internal:
    driver: bridge
